[package]
name = "neutrino"
version = "0.1.0"
edition = "2024"

[dependencies]
bluer = "0.17.4"
serialport = "4.10.1"

[profile.release]
opt-level = 3      # Optimize for size (use "s" or "z")
strip = true         # Automatically strip symbols from the binary
lto = true           # Enable Link-Time Optimization (removes unused code)
codegen-units = 1    # Reduce parallel code generation blocks for better size optimization
#panic = "abort"      # Remove panic unwinding machinery (app crashes immediately on panic)
